### ISSUE TITLE
PDF Reader Pro - 50% OFF, Special Discounts for Students & Professors, Permanent License

### ISSUE THREAD

**Issue by yiqideren** [AchoArnold/discount-for-student-dev#101]
PDF Reader Pro is an all in one PDF office supporting to Read, Annotate, Edit, OCR, Convert, Create & Fill Form, Sign PDFs on Mac, iOS, Android, and Windows

Could I Download 7-day Free trial of PDF Reader Pro for Mac?
https://www.pdfreaderpro.com/help/differences-between-free-and-edition-version

50% OFF, Special Discounts for Students & Professors, Permanent License
https://www.pdfreaderpro.com/store

https://www.pdfreaderpro.com/help

PDF Reader Pro for iOS, Android, Mac and Windows
https://www.pdfreaderpro.com/product

50% OFF, Back to School Sale! Permanent License
https://www.pdfreaderpro.com/back-to-school

**Comment by AchoArnold** [comment]
Closing this in favor of https://github.com/AchoArnold/discount-for-student-dev/issues/102
