### ISSUE TITLE
Filmage Screen - 50% OFF, Special Discounts for Students & Professors, Lifetime License

### ISSUE THREAD

**Issue by yiqideren** [AchoArnold/discount-for-student-dev#102]
Filmage Screen is an all-in-one video toolbox, you can record HD video, edit video, make animated GIFs, convert video and do more on your Mac.

50% OFF, Special Discounts for Students & Professors, Lifetime License
https://www.filmagepro.com/store

Filmage Screen - The Best Screen Recorder & Video Editor & Converter for Mac
https://apps.apple.com/us/app/filmage-screen-screen-recorder/id1475049179?mt=12

Could I Download 7-day Free trial of Filmage Screen for Mac?
https://www.filmagepro.com/help/differences-between-free-and-pro-version

50% OFF, Back to School Sale! Lifetime License
https://www.filmagepro.com

**Comment by AchoArnold** [comment]
Hey @yiqideren  Do you have a page with more information about the discount which is specific for students? Also I think you can create a PR with that link please take a look at the contribution guide https://github.com/AchoArnold/discount-for-student-dev/blob/master/contributing.md
