### ISSUE TITLE
Filmage Converter - Best video converter and editor for Mac and Android

### ISSUE THREAD

**Issue by yiqideren** [AchoArnold/discount-for-student-dev#103]
Filmage Converter is the best video converter. You can convert videos to any formats like MOV, MP4, MKV. You can crop, rotate, and merge video clips. Now have a try.

https://www.filmagepro.com/filmageconverter

https://apps.apple.com/us/app/filmage-converter-videoconvert/id1475051167

50% OFF, Back to School Sale! Permanent License
https://www.pdfreaderpro.com/back-to-school

**Comment by AchoArnold** [comment]
Closing this in favor of https://github.com/AchoArnold/discount-for-student-dev/issues/102
