### ISSUE TITLE
Build failed issue

### ISSUE THREAD

**Issue by MoshiulRabbi** [AchoArnold/discount-for-student-dev#113]
[Can you check whats the problem here](https://github.com/AchoArnold/discount-for-student-dev/pull/112)

**Comment by hiverkiya** [comment]
@AchoArnold Please check into it. I'm also facing issues because of this. Thanks! 🚀

**Comment by AchoArnold** [comment]
it's been fixed Thanks @MoshiulRabbi , @hiverkiya
