### ISSUE TITLE
Storyscript gives 404 when trying to access

### ISSUE THREAD

**Issue by gr3yta5ks** [AchoArnold/discount-for-student-dev#117]
also I haven't been able to locate where to register now or signin using GItHub. Thought it was just me but other student accounts seeing the same. https://storyscript.io/github-student-pack

**Comment by hiverkiya** [comment]
Yes, It might be possible that it's not available anymore. The same happened with the Flatiron Bootcamp service. Raising a PR in reference to this issue would be nice! 🚀 Have a nice day! 💯

**Comment by AchoArnold** [comment]
I checked and I couldn't find any information about story script. Thanks @gr3yta5ks , @hiverkiya
