### ISSUE TITLE
O'Reilly update

### ISSUE THREAD

**Issue by jtrim-ons** [AchoArnold/discount-for-student-dev#126]
The O'Reilly membership through ACM doesn't require an ACM Digital Library subscription; it just needs ACM Membership.

However, since about a month ago, O'Reilly is no longer provided with an ACM student membership. One option is to get an ACM professional membership for $99 per year. I think there is a way to pay a supplement on top of the student membership to get access to O'Reilly, but I don't know if the details are published on the ACM website.

See https://learning.acm.org/faq/oreilly-faqs

**Comment by lmeerwood** [comment]
I just submitted a pull request to remove the O'Reilly information. It has been removed altogether from ACM memberships.
