### ISSUE TITLE
weird redirect and possible dead links

### ISSUE THREAD

**Issue by z00rat** [AchoArnold/discount-for-student-dev#136]
hi,
i found some problem with this repo.
in here i will list all the problems
and later today i will make a pull request with some fix(mostly redirects).

---

weird redirect:
- all https://education.github.com/pack/redeem/*  redirect to  https://education.github.com/pack
- 
- https://github.com/AchoArnold/discount-for-student-dev/blob/39e137f9e66dffa526801228afd3ef24e9d297cc/README.md?plain=1#L65
- https://github.com/AchoArnold/discount-for-student-dev/blob/39e137f9e66dffa526801228afd3ef24e9d297cc/README.md?plain=1#L203
- https://github.com/AchoArnold/discount-for-student-dev/blob/39e137f9e66dffa526801228afd3ef24e9d297cc/README.md?plain=1#L201
- https://github.com/AchoArnold/discount-for-student-dev/blob/39e137f9e66dffa526801228afd3ef24e9d297cc/README.md?plain=1#L220
- https://github.com/AchoArnold/discount-for-student-dev/blob/39e137f9e66dffa526801228afd3ef24e9d297cc/README.md?plain=1#L268
- https://github.com/AchoArnold/discount-for-student-dev/blob/39e137f9e66dffa526801228afd3ef24e9d297cc/README.md?plain=1#L392
- 

dead links:
- https://github.com/AchoArnold/discount-for-student-dev/blob/39e137f9e66dffa526801228afd3ef24e9d297cc/README.md?plain=1#L139
- https://github.com/AchoArnold/discount-for-student-dev/blob/39e137f9e66dffa526801228afd3ef24e9d297cc/README.md?plain=1#L156
- https://github.com/AchoArnold/discount-for-student-dev/blob/39e137f9e66dffa526801228afd3ef24e9d297cc/README.md?plain=1#L405

**Comment by AchoArnold** [comment]
Thanks for the PR

**Comment by z00rat** [comment]
> Thanks for the PR

no problem.

but why did you close this issue ??
those are the links i dont know how to fix.

please fix those.

**Comment by AchoArnold** [comment]
I closed this PR as a mistake.

I fixed the issues @z00rat 

Thanks for the feedback.
