### ISSUE TITLE
Specify discount amounts

### ISSUE THREAD

**Issue by Mortiferr** [AchoArnold/discount-for-student-dev#62]
Maybe differentiate between free and discounted. Some students can't or won't buy things, so it might be nice to differentiate.

**Comment by Verkiya** [comment]
Sir , Can i be of any help here ?

**Comment by Mortiferr** [comment]
Should we split up what's free and what's discounted completely or just put something next to it like [discount] / [free].

**Comment by Verkiya** [comment]
But if something's having both facilities then it'll b better to mention both! Anyway @Mortiferr Your Idea sounds good to me :100:

**Comment by AchoArnold** [comment]
I love the idea too @Mortiferr

**Comment by Mortiferr** [comment]
@AchoArnold I'll start a PR soon

**Comment by Mortiferr** [comment]
@AchoArnold Alright, I created a PR #67 that will close issues #66 and this one.

**Comment by AchoArnold** [comment]
Good Job @Mortiferr. Thanks very much 👍
