### ISSUE TITLE
Discount to O'Reilly Online Learning through the ACM

### ISSUE THREAD

**Issue by lmeerwood** [AchoArnold/discount-for-student-dev#77]
[O'Reilly's Online Learning](https://learning.oreilly.com) is a great resource with tons of books and training videos. It cost $39 a month or $399 a year. However, Computer Science and IT students can sign up to [ACM](https://www.acm.org/) (Association for Computing Machinery) at a great discount. As long as they sign up for a membership level that contains the Digital Library, then they will also get access to O'reilly's Online Learning platform.

The cheapest way is to sign up for **Student Membership PLUS Digital Library** which cost $42 a year. That is only 10% of the cost of signing up for a year through O'Reilly directly. 

I would make a pull request myself, but I am unsure of what section this would fall under.

**Comment by AchoArnold** [comment]
This is a tricky one @lmeerwood  Maybe we should create a new section for `courses`

**Comment by lmeerwood** [comment]
That's not a bad idea. It is really quite overwhelming the amount of content that is available on O'Reilly and being able to get it so cheap as a student would be a huge boon for many.

**Comment by AchoArnold** [comment]
Merged. Thanks @lmeerwood

**Comment by aidanh010** [comment]
Are you sure the Digital Library is required? I have the Membership with print CACM but not Digital Library and I still have access.

**Comment by lmeerwood** [comment]
That is interesting, I'll need to look further into this as I have always assumed you needed the digital library as part of it, not sure why I assumed that.
