### ISSUE TITLE
Update page with the latest tools from the Github Student Developer Pack

### ISSUE THREAD

**Issue by LeptoFlare** [AchoArnold/discount-for-student-dev#98]
Many new tools have been added since, and the page here should be updated to reflect them:
> https://education.github.com/pack/offers

**Comment by hiverkiya** [comment]
@LeptoFlare 👍  Why don't you create a PR with required changes and have @AchoArnold review it? That'll be awesome! ⭐

**Comment by LeptoFlare** [comment]
Hey! I'm not sure at what point is this repository updated to

**Comment by hiverkiya** [comment]
@LeptoFlare Not a problem. Follow these steps and you're good to go 👍 You can take help from Youtube Github resources if stuck. If you're still not able to do, I'll make the required changes.
Hope it helps you learn a bit more about GitHub 👍 🌟 💯 

- Fork/Clone the repository
- Make Changes required
- Create PR

**Comment by LeptoFlare** [comment]
... that's not what I'm stuck on.

How many benefits are catalogued on the repository?
I need to know where to start so I do not skip any benefits, or add duplicate ones.

**Comment by hiverkiya** [comment]
About that 🤔, I guess it hasn't been updated with recently added services. What I do is to search those services and add them if they don't exist.
However, sometimes services are deprecated as well like Bitnami one ( which they earlier used to offer ) , so have to keep them in check also.
In a nutshell, anyone have to see if services are there or not.
Happy coding (. ❛ ᴗ ❛.)

**Comment by AchoArnold** [comment]
@LeptoFlare @hiverkiya  to give you some context, I'm not a student anymore so I can't even access this page https://education.github.com/pack/offers

**Comment by hiverkiya** [comment]
Oh I got it ! No worries, I am a member of GitHub Education Pack. I'll make necessary changes in meantime (◍•ᴗ•◍)

**Comment by AchoArnold** [comment]
👍  thanks!

**Comment by AchoArnold** [comment]
Solved by #100
